# -*- coding: utf-8 -*-
"""Spotify.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1shf0j1e-oPehl2Ztd2l21Lu2QUXJnbK5
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("ambaliyagati/spotify-dataset-for-playing-around-with-sql")

print("Path to dataset files:", path)

df_path = '/kaggle/input/spotify-dataset-for-playing-around-with-sql/spotify_tracks.csv'

import pandas as pd
df = pd.read_csv(df_path)

print(df.info())
print(df.head())
print(f"Размер датасета: {df.shape}")

print(f"Number of duplicate rows: {df.duplicated().sum()}")

pip install musicbrainzngs

import gdown
file_id = "1wHxeDoYIbW6HP7KEsMjJEtfVaex22Rqy"
output_file = "musicbrainz_artist_cache.json"

print(f"\nЗагрузка файла 'musicbrainz_artist_cache.json' из Google Drive...")
print(f"File ID: {file_id}")

try:
    # Скачиваем файл
    gdown.download(
        url=f"https://drive.google.com/uc?id={file_id}",
        output=output_file,
        quiet=False  # Показываем прогресс загрузки
    )
    print(f"\n✅ Файл успешно загружен: {output_file}")
except Exception as e:
    print(f"\n⚠️ Ошибка при загрузке: {e}")

file_id_album = "11avDywD_Loc29yk8LUwogrh6MCY5XPVM"
output_file_album = "musicbrainz_cache.json"

print(f"\nЗагрузка файла 'musicbrainz_cache.json' из Google Drive...")
print(f"File ID: {file_id_album}")

try:
    # Скачиваем файл
    gdown.download(
        url=f"https://drive.google.com/uc?id={file_id_album}",
        output=output_file_album,
        quiet=False  # Показываем прогресс загрузки
    )
    print(f"\n✅ Файл успешно загружен: {output_file_album}")

except Exception as e:
    print(f"\n⚠️ Ошибка при загрузке: {e}")

import musicbrainzngs as mb
import time
import numpy as np
import pandas as pd
import json
import os
from tqdm.notebook import tqdm # Import tqdm for progress bar

# Set user agent for MusicBrainz API
mb.set_useragent("ColabDataAnalysisApp", "1.0", "gareevaazalia12@gmail.com")

# --- Cache for Album Information ---
CACHE_FILE = 'musicbrainz_cache.json'

def load_cache():
    """Loads the album cache from a JSON file."""
    if os.path.exists(CACHE_FILE):
        with open(CACHE_FILE, 'r') as f:
            loaded_cache = json.load(f)
            # Convert string 'nan' back to np.nan if necessary (None in JSON -> np.nan in Python)
            return {k: (v[0], v[1], v[2], (np.nan if v[3] is None else v[3]), v[4]) for k, v in loaded_cache.items()}
    return {}

def save_cache(cache_data):
    """Saves the album cache to a JSON file."""
    # Convert np.nan to None for JSON serialization
    serializable_cache = {k: (v[0], v[1], v[2], (None if pd.isna(v[3]) else v[3]), v[4]) for k, v in cache_data.items()}
    with open(CACHE_FILE, 'w') as f:
        json.dump(serializable_cache, f, indent=4)


def get_musicbrainz_album_info(artist_name, album_title, cache):
    """
    Fetches release metadata (country, status, label, year) for an album from MusicBrainz.
    Handles API rate limits, uses a cache, and returns default values if no information is found.
    """
    cache_key = f"{artist_name}|{album_title}"

    if cache_key in cache:
        return cache[cache_key]

    retries = 3
    for attempt in range(retries):
        try:
            time.sleep(1) # Adhere to MusicBrainz API rate limit (1 request per second)
            result = mb.search_releases(artist=artist_name, release=album_title, limit=1)

            country, status, label, year, has_data = 'unknown', 'unknown', 'unknown', np.nan, 0

            if result and result['release-list']:
                release = result['release-list'][0]
                country = release.get('country', 'unknown')
                status = release.get('status', 'unknown')

                if 'label-info' in release and release['label-info']:
                    label = release['label-info'][0].get('label', {}).get('name', 'unknown')

                if 'date' in release and release['date']:
                    try:
                        year = int(release['date'].split('-')[0])
                    except ValueError:
                        pass # year remains NaN if parsing fails
                has_data = 1 # Data found

            # Store result in cache before returning
            cache[cache_key] = (country, status, label, year, has_data)
            return country, status, label, year, has_data

        except mb.WebServiceError as e:
            print(f"MusicBrainz API error for {artist_name} - {album_title} (attempt {attempt+1}/{retries}): {e}")
            if attempt < retries - 1:
                time.sleep(5) # Wait longer before retrying
            else:
                # After all retries fail, store and return defaults
                cache[cache_key] = ('unknown', 'unknown', 'unknown', np.nan, 0)
                return 'unknown', 'unknown', 'unknown', np.nan, 0
        except Exception as e:
            print(f"An unexpected error occurred for {artist_name} - {album_title}: {e}")
            # Store and return defaults for unexpected errors
            cache[cache_key] = ('unknown', 'unknown', 'unknown', np.nan, 0)
            return 'unknown', 'unknown', 'unknown', np.nan, 0

    # Fallback if all retries fail
    cache[cache_key] = ('unknown', 'unknown', 'unknown', np.nan, 0)
    return 'unknown', 'unknown', 'unknown', np.nan, 0


# Ensure the necessary album columns exist before trying to update them
if 'release_country' not in df.columns:
    df['release_country'] = 'unknown'
if 'release_status' not in df.columns:
    df['release_status'] = 'unknown'
if 'release_label' not in df.columns:
    df['release_label'] = 'unknown'
if 'album_year' not in df.columns:
    df['album_year'] = np.nan
if 'has_musicbrainz_data' not in df.columns:
    df['has_musicbrainz_data'] = 0

# Create a temporary DataFrame of unique artist-album pairs to reduce redundant API calls
unique_albums_df = df[['artists', 'album']].drop_duplicates().copy()

# Load existing album cache
musicbrainz_album_cache = load_cache()
print(f"Loaded {len(musicbrainz_album_cache)} items from album cache.")

# Initialize columns in unique_albums_df DataFrame to store fetched data
unique_albums_df['mb_release_country'] = 'unknown'
unique_albums_df['mb_release_status'] = 'unknown'
unique_albums_df['mb_release_label'] = 'unknown'
unique_albums_df['mb_album_year'] = np.nan
unique_albums_df['mb_has_data'] = 0

print(f"Fetching MusicBrainz album data for {len(unique_albums_df)} unique album-artist pairs...")

processed_album_count = 0
# Apply the function to each unique album, checking cache first
for index, row in tqdm(unique_albums_df.iterrows(), total=len(unique_albums_df), desc="Fetching Album Data"):
    country, status, label, year, has_data = get_musicbrainz_album_info(row['artists'], row['album'], musicbrainz_album_cache)

    unique_albums_df.loc[index, 'mb_release_country'] = country
    unique_albums_df.loc[index, 'mb_release_status'] = status
    unique_albums_df.loc[index, 'mb_release_label'] = label
    unique_albums_df.loc[index, 'mb_album_year'] = year
    unique_albums_df.loc[index, 'mb_has_data'] = has_data

    processed_album_count += 1
    if processed_album_count % 100 == 0: # Save cache periodically
        save_cache(musicbrainz_album_cache)
        # print(f"Processed {processed_album_count} albums. Album cache saved.") # Removed to avoid cluttering with tqdm

# Save the cache one last time after the loop completes
save_cache(musicbrainz_album_cache)
print(f"\nAll {processed_album_count} albums processed. Final album cache saved.")

# Merge the fetched album data back to the original DataFrame
df = df.merge(unique_albums_df, on=['artists', 'album'], how='left', suffixes=('', '_mb_album'))

# Update the original df columns with the new fetched data (only if mb_has_data is 1)
df['release_country'] = np.where(df['mb_has_data'] == 1, df['mb_release_country'], df['release_country'])
df['release_status'] = np.where(df['mb_has_data'] == 1, df['mb_release_status'], df['release_status'])
df['release_label'] = np.where(df['mb_has_data'] == 1, df['mb_release_label'], df['release_label'])
df['album_year'] = np.where(df['mb_has_data'] == 1, df['mb_album_year'], df['album_year'])
df['has_musicbrainz_data'] = np.where(df['mb_has_data'] == 1, 1, df['has_musicbrainz_data'])

# Drop the temporary album columns created during the merge
df = df.drop(columns=['mb_release_country', 'mb_release_status', 'mb_release_label', 'mb_album_year', 'mb_has_data'])


# --- New Artist Information Fetching ---
ARTIST_CACHE_FILE = 'musicbrainz_artist_cache.json'

def load_artist_cache():
    """Loads the artist cache from a JSON file."""
    if os.path.exists(ARTIST_CACHE_FILE):
        with open(ARTIST_CACHE_FILE, 'r') as f:
            loaded_cache = json.load(f)
            # Convert string 'nan' back to np.nan (None in JSON -> np.nan in Python)
            return {k: (v[0], v[1], (np.nan if v[2] is None else v[2]), (np.nan if v[3] is None else v[3]), v[4], v[5]) for k, v in loaded_cache.items()}
    return {}

def save_artist_cache(cache_data):
    """Saves the artist cache to a JSON file."""
    # Convert np.nan to None for JSON serialization
    serializable_cache = {k: (v[0], v[1], (None if pd.isna(v[2]) else v[2]), (None if pd.isna(v[3]) else v[3]), v[4], v[5]) for k, v in cache_data.items()}
    with open(ARTIST_CACHE_FILE, 'w') as f:
        json.dump(serializable_cache, f, indent=4)

def get_musicbrainz_artist_details(artist_name, artist_cache):
    """
    Fetches artist metadata (type, country, career dates) from MusicBrainz.
    Handles API rate limits, uses a cache, and returns default values if no information is found.
    """
    cache_key = artist_name
    if cache_key in artist_cache:
        return artist_cache[cache_key]

    # Take the first artist if there's a comma-separated list for lookup simplicity
    primary_artist = artist_name.split(',')[0].strip()

    retries = 3
    for attempt in range(retries):
        try:
            time.sleep(1) # Adhere to MusicBrainz API rate limit
            result = mb.search_artists(artist=primary_artist, limit=1)

            artist_type, country, begin_year, end_year, is_active, has_data = 'unknown', 'unknown', np.nan, np.nan, False, 0

            if result and result['artist-list']:
                artist = result['artist-list'][0]
                artist_type = artist.get('type', 'unknown')
                country = artist.get('country', 'unknown')

                if 'life-span' in artist:
                    begin_date = artist['life-span'].get('begin')
                    if begin_date:
                        try:
                            begin_year = int(begin_date.split('-')[0])
                        except ValueError:
                            pass
                    end_date = artist['life-span'].get('end')
                    if end_date:
                        try:
                            end_year = int(end_date.split('-')[0])
                        except ValueError:
                            pass
                # An artist is considered active if no end date or end date is in the future/current year, and a begin year is known.
                is_active = (pd.isna(end_year) or (not pd.isna(end_year) and end_year >= pd.Timestamp.now().year)) and not pd.isna(begin_year)
                has_data = 1

            artist_cache[cache_key] = (artist_type, country, begin_year, end_year, is_active, has_data)
            return artist_type, country, begin_year, end_year, is_active, has_data

        except mb.WebServiceError as e:
            print(f"MusicBrainz API error for artist {primary_artist} (attempt {attempt+1}/{retries}): {e}")
            if attempt < retries - 1:
                time.sleep(5)
            else:
                artist_cache[cache_key] = ('unknown', 'unknown', np.nan, np.nan, False, 0)
                return 'unknown', 'unknown', np.nan, np.nan, False, 0
        except Exception as e:
            print(f"An unexpected error occurred for artist {primary_artist}: {e}")
            artist_cache[cache_key] = ('unknown', 'unknown', np.nan, np.nan, False, 0)
            return 'unknown', 'unknown', np.nan, np.nan, False, 0
    artist_cache[cache_key] = ('unknown', 'unknown', np.nan, np.nan, False, 0)
    return 'unknown', 'unknown', np.nan, np.nan, False, 0

# Add new artist columns to df if they don't exist
if 'artist_type' not in df.columns:
    df['artist_type'] = 'unknown'
if 'artist_country' not in df.columns:
    df['artist_country'] = 'unknown'
if 'artist_begin_year' not in df.columns:
    df['artist_begin_year'] = np.nan
if 'artist_end_year' not in df.columns:
    df['artist_end_year'] = np.nan
if 'artist_is_active' not in df.columns:
    df['artist_is_active'] = False
if 'has_musicbrainz_artist_data' not in df.columns:
    df['has_musicbrainz_artist_data'] = 0

# Get unique artists to fetch details for
unique_artists_df = df[['artists']].drop_duplicates().copy()
unique_artists_df['mb_artist_type'] = 'unknown'
unique_artists_df['mb_artist_country'] = 'unknown'
unique_artists_df['mb_artist_begin_year'] = np.nan
unique_artists_df['mb_artist_end_year'] = np.nan
unique_artists_df['mb_artist_is_active'] = False
unique_artists_df['mb_has_artist_data'] = 0

artist_cache = load_artist_cache()
print(f"Loaded {len(artist_cache)} items from artist cache.")

print(f"Fetching MusicBrainz artist data for {len(unique_artists_df)} unique artists...")

processed_artist_count = 0
for index, row in tqdm(unique_artists_df.iterrows(), total=len(unique_artists_df), desc="Fetching Artist Data"):
    artist_type, country, begin_year, end_year, is_active, has_data = get_musicbrainz_artist_details(row['artists'], artist_cache)
    unique_artists_df.loc[index, 'mb_artist_type'] = artist_type
    unique_artists_df.loc[index, 'mb_artist_country'] = country
    unique_artists_df.loc[index, 'mb_artist_begin_year'] = begin_year
    unique_artists_df.loc[index, 'mb_artist_end_year'] = end_year
    unique_artists_df.loc[index, 'mb_artist_is_active'] = is_active
    unique_artists_df.loc[index, 'mb_has_artist_data'] = has_data

    processed_artist_count += 1
    if processed_artist_count % 50 == 0: # Save cache periodically
        save_artist_cache(artist_cache)
        # print(f"Processed {processed_artist_count} artists. Artist cache saved.") # Removed to avoid cluttering with tqdm

save_artist_cache(artist_cache)
print(f"\nAll {processed_artist_count} artists processed. Final artist cache saved.")

# Merge artist data back to the main DataFrame
df = df.merge(unique_artists_df, on='artists', how='left', suffixes=('', '_mb_artist'))

# Update original df artist columns with fetched data (only if mb_has_artist_data is 1)
df['artist_type'] = np.where(df['mb_has_artist_data'] == 1, df['mb_artist_type'], df['artist_type'])
df['artist_country'] = np.where(df['mb_has_artist_data'] == 1, df['mb_artist_country'], df['artist_country'])
df['artist_begin_year'] = np.where(df['mb_has_artist_data'] == 1, df['mb_artist_begin_year'], df['artist_begin_year'])
df['artist_end_year'] = np.where(df['mb_has_artist_data'] == 1, df['mb_artist_end_year'], df['artist_end_year'])
df['artist_is_active'] = np.where(df['mb_has_artist_data'] == 1, df['mb_artist_is_active'], df['artist_is_active'])
df['has_musicbrainz_artist_data'] = np.where(df['mb_has_artist_data'] == 1, 1, df['has_musicbrainz_artist_data'])

# Drop temporary artist merge columns
df = df.drop(columns=['mb_artist_type', 'mb_artist_country', 'mb_artist_begin_year', 'mb_artist_end_year', 'mb_artist_is_active', 'mb_has_artist_data'])

# Calculate artist career duration (стаж) if begin year is known
df['artist_career_duration_years'] = np.where(
    df['has_musicbrainz_artist_data'] == 1,
    np.where(
        df['artist_begin_year'].notna(),
        (df['artist_end_year'].fillna(pd.Timestamp.now().year) - df['artist_begin_year']),
        np.nan
    ),
    np.nan
)
# If start and end are same year, or if it's active and current year is start year, duration might be 0, replace with nan if desired.
df['artist_career_duration_years'] = df['artist_career_duration_years'].replace(0, np.nan)

print("\nMusicBrainz album and artist data fetching and merging complete.")
print("Updated DataFrame info with all new details:")
df.info()
print("\nFirst 5 rows with updated MusicBrainz data (album and artist):")
display(df[['artists', 'album', 'release_country', 'release_status', 'release_label', 'album_year', 'has_musicbrainz_data', \
            'artist_type', 'artist_country', 'artist_begin_year', 'artist_end_year', 'artist_is_active', 'artist_career_duration_years', 'has_musicbrainz_artist_data']].head())

df.info()

"""### Объединение 126 уникальных жанров в 5 супер-жанров

Чтобы уменьшить размерность категориального признака 'genre', мы сгруппируем его в 5 более широких категорий (супер-жанров). Это поможет упростить модель и выявить более общие закономерности.
"""

def map_genre_to_super_genre(genre):
    genre = str(genre).lower() # Приводим к нижнему регистру для сравнения

    # Категория 1: Electronic / Pop (Электронная / Поп-музыка)
    electronic_pop_genres = [
        'pop', 'dance pop', 'electropop', 'pop rap', 'indie pop', 'synth-pop',
        'dance', 'electronic', 'edm', 'house', 'techno', 'trance', 'dubstep',
        'drum and bass', 'electro', 'synthwave', 'disco', 'k-pop', 'j-pop',
        'ambient pop', 'vaporwave'
    ]

    # Категория 2: Rock / Alternative (Рок / Альтернатива)
    rock_alternative_genres = [
        'rock', 'alternative rock', 'indie rock', 'punk', 'metal', 'hard rock',
        'classic rock', 'progressive rock', 'new wave', 'post-punk', 'grunge',
        'folk rock', 'alt-metal', 'punk rock', 'heavy metal', 'alternative'
    ]

    # Категория 3: Hip-Hop / R&B / Soul (Хип-Хоп / R&B / Соул)
    hiphop_rnb_soul_genres = [
        'hip hop', 'rap', 'r&b', 'soul', 'trap', 'gangsta rap', 'conscious hip hop',
        'g-funk', 'neo soul', 'funk', 'old school hip hop'
    ]

    # Категория 4: Acoustic / Folk / Country (Акустика / Фолк / Кантри)
    acoustic_folk_country_genres = [
        'acoustic', 'folk', 'country', 'blues', 'jazz', 'singer-songwriter',
        'americana', 'bluegrass', 'country pop', 'gospel'
    ]

    if any(g in genre for g in electronic_pop_genres):
        return 'Electronic/Pop'
    elif any(g in genre for g in rock_alternative_genres):
        return 'Rock/Alternative'
    elif any(g in genre for g in hiphop_rnb_soul_genres):
        return 'Hip-Hop/R&B/Soul'
    elif any(g in genre for g in acoustic_folk_country_genres):
        return 'Acoustic/Folk/Country'
    else:
        # Категория 5: World / Classical / Other (Мировая / Классическая / Прочее)
        return 'World/Classical/Other'

df['super_genre'] = df['genre'].apply(map_genre_to_super_genre)

print("Распределение новых супер-жанров:")
display(df['super_genre'].value_counts())

# Если вы хотите заменить исходный столбец 'genre' новым, выполните следующую строку:
# df['genre'] = df['super_genre']
# df = df.drop(columns=['super_genre'])

import datetime

# Get the current year
current_year = datetime.datetime.now().year

# Calculate album age. If 'album_year' is missing, 'album_age_years' will be NaN.
df['album_age_years'] = current_year - df['album_year']

print("Добавлен столбец 'album_age_years'.\n")
print("Первые 5 строк с новым столбцом:")
display(df[['album', 'album_year', 'album_age_years']].head())

print("\nСтатистика для 'album_age_years':")
display(df['album_age_years'].describe())

columns_to_drop = ['id', 'genre', 'album_year', 'artist_begin_year', 'artist_end_year']
df = df.drop(columns=columns_to_drop)

print(f"Столбцы {', '.join(columns_to_drop)} были удалены.\n")
print("Обновленная информация о датасете:")
df.info()

display(df)

"""### Identifying and Transforming Categorical Variables"""

# Identify categorical columns
categorical_cols = df.select_dtypes(include=['object', 'bool']).columns
print("Categorical columns identified:", list(categorical_cols))

"""### One-Hot Encoding Categorical Features

Применим One-Hot Encoding к категориальным признакам, чтобы преобразовать их в числовой формат, подходящий для моделей машинного обучения.
"""

# Определяем категориальные столбцы, которые нужно закодировать.
# 'explicit' и 'artist_is_active' уже булевы, поэтому их можно просто преобразовать в int.
categorical_to_encode = [
    'release_country', 'release_status', 'release_label', 'artist_type', 'artist_country', 'super_genre'
]

# Для начала, преобразуем булевы столбцы в int (0 или 1), если они не были преобразованы ранее.
# Проверим, существуют ли столбцы и имеют ли они тип bool, прежде чем пытаться преобразовать.
if 'explicit' in df.columns and df['explicit'].dtype == 'bool':
    df['explicit'] = df['explicit'].astype(int)
    print("Столбец 'explicit' преобразован в int.")

if 'artist_is_active' in df.columns and df['artist_is_active'].dtype == 'bool':
    df['artist_is_active'] = df['artist_is_active'].astype(int)
    print("Столбец 'artist_is_active' преобразован в int.")

# Применяем One-Hot Encoding к выбранным категориальным столбцам
df_encoded = pd.get_dummies(df, columns=categorical_to_encode, drop_first=True, dtype=int)

print(f"Преобразовано {len(categorical_to_encode)} категориальных столбцов.")
print("Размер датасета после One-Hot Encoding:", df_encoded.shape)

print("\nПервые 5 строк обновленного датасета (с некоторыми закодированными столбцами):")
display(df_encoded.head())

print("\nИнформация о датасете после кодирования:")
df_encoded.info()

"""### Analyzing Numerical Feature Distributions and Handling Outliers"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Identify numerical columns in the current df
# Exclude 'genre_encoded' if it's considered a categorical feature for outlier analysis, or include if treated numerically.
# For now, let's treat 'genre_encoded' as numerical for distribution analysis.
numerical_cols = df.select_dtypes(include=np.number).columns.tolist()

print("Numerical columns identified for distribution analysis:", numerical_cols)

"""#### Visualizing Distributions (Histograms and Box Plots)"""

for col in numerical_cols:
    print(f"\nAnalyzing column: {col}")
    fig, axes = plt.subplots(1, 2, figsize=(15, 5))

    # Histogram
    sns.histplot(df[col], kde=True, ax=axes[0])
    axes[0].set_title(f'Distribution of {col}')

    # Box Plot
    sns.boxplot(y=df[col], ax=axes[1])
    axes[1].set_title(f'Box Plot of {col}')

    plt.tight_layout()
    plt.show()

"""#### Outlier Detection using IQR Method"""

for col in numerical_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound_iqr = Q1 - 1.5 * IQR
    upper_bound_iqr = Q3 + 1.5 * IQR

    outliers_iqr = df[(df[col] < lower_bound_iqr) | (df[col] > upper_bound_iqr)]

    print(f"\nColumn: {col} (IQR Method)")
    print(f"  Q1: {Q1:.2f}, Q3: {Q3:.2f}, IQR: {IQR:.2f}")
    print(f"  Lower Bound: {lower_bound_iqr:.2f}, Upper Bound: {upper_bound_iqr:.2f}")
    print(f"  Number of outliers: {len(outliers_iqr)}")
    if len(outliers_iqr) > 0:
        print("  Outliers (first 5):")
        display(outliers_iqr[[col]].head())

"""#### Handling Outliers in 'duration_ms' and 'album_age_years' columns (Capping with IQR)"""

# Capping for 'duration_ms'
Q1_duration = df['duration_ms'].quantile(0.25)
Q3_duration = df['duration_ms'].quantile(0.75)
IQR_duration = Q3_duration - Q1_duration

lower_bound_duration = Q1_duration - 1.5 * IQR_duration
upper_bound_duration = Q3_duration + 1.5 * IQR_duration

print(f"Original 'duration_ms' - Q1: {Q1_duration:.2f}, Q3: {Q3_duration:.2f}, IQR: {IQR_duration:.2f}")
print(f"Lower Bound for Capping: {lower_bound_duration:.2f}, Upper Bound for Capping: {upper_bound_duration:.2f}")

df['duration_ms_capped'] = df['duration_ms'].clip(lower=lower_bound_duration, upper=upper_bound_duration)

print("\nDescriptive statistics for 'duration_ms' after capping:")
display(df[['duration_ms', 'duration_ms_capped']].describe())

# Visualize 'duration_ms' after capping
plt.figure(figsize=(10, 6))
sns.boxplot(y=df['duration_ms_capped'])
plt.title('Box Plot of Duration (After Outlier Capping)')
plt.ylabel('Duration (Capped)')
plt.show()

print(f"Number of values changed due to capping in 'duration_ms': {(df['duration_ms'] != df['duration_ms_capped']).sum()}")

# Capping for 'album_age_years'
# Note: album_age_years has NaNs, which need to be handled. Capping will ignore NaNs by default.
Q1_age = df['album_age_years'].quantile(0.25)
Q3_age = df['album_age_years'].quantile(0.75)
IQR_age = Q3_age - Q1_age

lower_bound_age = Q1_age - 1.5 * IQR_age
upper_bound_age = Q3_age + 1.5 * IQR_age

print(f"\nOriginal 'album_age_years' - Q1: {Q1_age:.2f}, Q3: {Q3_age:.2f}, IQR: {IQR_age:.2f}")
print(f"Lower Bound for Capping: {lower_bound_age:.2f}, Upper Bound for Capping: {upper_bound_age:.2f}")

df['album_age_years_capped'] = df['album_age_years'].clip(lower=lower_bound_age, upper=upper_bound_age)

print("\nDescriptive statistics for 'album_age_years' after capping:")
display(df[['album_age_years', 'album_age_years_capped']].describe())

# Visualize 'album_age_years' after capping
plt.figure(figsize=(10, 6))
sns.boxplot(y=df['album_age_years_capped'])
plt.title('Box Plot of Album Age (After Outlier Capping)')
plt.ylabel('Album Age (Capped)')
plt.show()

print(f"Number of values changed due to capping in 'album_age_years': {(df['album_age_years'] != df['album_age_years_capped']).sum()}")

# Capping for 'popularity'
# Note: popularity has NaNs, which need to be handled. Capping will ignore NaNs by default.
Q1_popularity = df['popularity'].quantile(0.25)
Q3_popularity = df['popularity'].quantile(0.75)
IQR_popularity = Q3_popularity - Q1_popularity

lower_bound_popularity = Q1_popularity - 1.5 * IQR_popularity
upper_bound_popularity = Q3_popularity + 1.5 * IQR_popularity

print(f"\nOriginal 'popularity' - Q1: {Q1_popularity:.2f}, Q3: {Q3_popularity:.2f}, IQR: {IQR_popularity:.2f}")
print(f"Lower Bound for Capping: {lower_bound_popularity:.2f}, Upper Bound for Capping: {upper_bound_popularity:.2f}")

df['popularity_capped'] = df['popularity'].clip(lower=lower_bound_popularity, upper=upper_bound_popularity)

print("\nDescriptive statistics for 'popularity' after capping:")
display(df[['popularity', 'popularity_capped']].describe())

# Visualize 'popularity' after capping
plt.figure(figsize=(10, 6))
sns.boxplot(y=df['popularity_capped'])
plt.title('Box Plot of Popularity (After Outlier Capping)')
plt.ylabel('Popularity (Capped)')
plt.show()

print(f"Number of values changed due to capping in 'popularity': {(df['popularity'] != df['popularity_capped']).sum()}")

"""### Removing Original Numerical Columns"""

columns_to_remove = ['popularity', 'duration_ms', 'album_age_years', 'has_musicbrainz_data', 'has_musicbrainz_artist_data']
df = df.drop(columns=columns_to_remove)

print(f"Original columns {', '.join(columns_to_remove)} removed from DataFrame.")
print("\nUpdated DataFrame info:")
df.info()

print("="*60)
print("КОЛОНКИ В df:")
print("="*60)
print(df.columns.tolist())

print("\n" + "="*60)
print("КОЛОНКИ В df_encoded:")
print("="*60)
print(df_encoded.columns.tolist())

columns_to_remove = ['popularity', 'duration_ms', 'album_age_years', 'has_musicbrainz_data', 'has_musicbrainz_artist_data']
df_encoded = df_encoded.drop(columns=columns_to_remove)

print(f"Original columns {', '.join(columns_to_remove)} removed from DataFrame.")
print("\nUpdated DataFrame info:")
df_encoded.info()

# Колонки в df
df_cols = set(df.columns)
print(f"Колонок в df: {len(df_cols)}")
# Колонки в df_encoded
df_encoded_cols = set(df_encoded.columns)
print(f"Колонок в df_encoded: {len(df_encoded_cols)}")

# Общие колонки
common_cols = df_cols.intersection(df_encoded_cols)
print(f"Общих колонок: {len(common_cols)}")
if common_cols:
    print(f"  {sorted(common_cols)}")

numeric_features_from_df = [
    'explicit',                         # бинарный (0/1)
    'artist_is_active',                 # бинарный (0/1)
    'artist_career_duration_years',     # стаж исполнителя (лет)
    'duration_ms_capped',               # длительность (обработанная)
    'album_age_years_capped',           # возраст альбома (обработанный)
    'popularity_capped'
]
df_numeric = df[numeric_features_from_df].copy()
print(f"   df_numeric: {df_numeric.shape}")

if not df_numeric.index.equals(df_encoded.index):
    print("⚠️ Индексы не совпадают! Выполняем сброс индексов...")
    df_numeric = df_numeric.reset_index(drop=True)
    df_encoded = df_encoded.reset_index(drop=True)

# Объединяем по горизонтали
df_final = pd.concat([df_numeric, df_encoded], axis=1)

print(f"✅ df_final создан: {df_final.shape}")
print(f"   Колонок: {len(df_final.columns)}")
print(f"   Записей: {len(df_final)}")

"""### Исследование дублирования столбцов в `df_final`"""

print(f"\nВсе колонки в df_final ({len(df_final.columns)}):")
print(df_final.columns.tolist())

print("\n--- 1. Проверка дублирующихся названий колонок ---")

# Проверяем дублирующиеся названия
duplicate_names = df_final.columns[df_final.columns.duplicated()].tolist()
if duplicate_names:
    print(f"Найдены дублирующиеся названия колонок: {duplicate_names}")
    # Удаляем дубликаты названий (оставляем только первые)
    df_final = df_final.loc[:, ~df_final.columns.duplicated(keep='first')]
    print(f"Дубликаты названий удалены, df_final: {df_final.shape}")
else:
    print("Дублирующихся названий колонок нет")


print("\n--- 2. Проверка дублирующихся колонок по содержанию ---")

# Выбираем только числовые колонки
df_numeric_only = df_final.select_dtypes(include=[np.number]).copy()

# Словарь для хранения хэшей колонок
seen_hashes = {}
duplicate_content_cols = []

print(f"Проверка {len(df_numeric_only.columns)} числовых колонок...")

for col in df_numeric_only.columns:
    # Проверяем, есть ли в колонке значения
    if df_numeric_only[col].isnull().all():
        continue

    # Заменяем NaN на уникальное значение для корректного сравнения
    col_values = df_numeric_only[col].fillna('NaN_' + col)

    # Вычисляем хэш
    col_hash = hash(tuple(col_values.values))

    if col_hash in seen_hashes:
        duplicate_content_cols.append(col)
        print(f"Дубликат найден: '{col}' (совпадает с '{seen_hashes[col_hash]}')")
    else:
        seen_hashes[col_hash] = col

if duplicate_content_cols:
    print(f"\n Найдены дублирующиеся колонки по содержанию: {duplicate_content_cols}")
    print("Удаляем дубликаты...")

    # Удаляем дубликаты, оставляя первую колонку
    df_final = df_final.drop(columns=duplicate_content_cols)
    print(f"Дубликаты удалены, df_final: {df_final.shape}")
else:
    print("Дублирующихся колонок по содержанию нет")

print("\n--- 3. Проверка константных колонок ---")

constant_cols = []
for col in df_final.columns:
    if df_final[col].nunique() == 1:
        constant_cols.append(col)
        print(f"Константная колонка: '{col}' (все значения = {df_final[col].iloc[0]})")

if constant_cols:
    print(f"\nНайдены константные колонки: {constant_cols}")
    print("Удаляем константные колонки...")
    df_final = df_final.drop(columns=constant_cols)
    print(f"Константные колонки удалены, df_final: {df_final.shape}")
else:
    print("Константных колонок нет")

print("\n--- 4. Итоговая проверка ---")

print(f"\n Итоговый df_final: {df_final.shape}")
print(f"   Колонок: {len(df_final.columns)}")
print(f"   Записей: {len(df_final)}")

# Проверка пропусков
null_count = df_final.isnull().sum().sum()
print(f"Пропусков: {null_count}")

if null_count == 0:
    print("Пропусков нет!")
else:
    print(f"Есть {null_count} пропусков!")
    print("\nКолонки с пропусками:")
    print(df_final.isnull().sum()[df_final.isnull().sum() > 0])

print("До обработки пропущенных значений:")
print(df_final[['artist_career_duration_years', 'album_age_years_capped']].isnull().sum())

# Заполняем пропуски в 'artist_career_duration_years' нулями
df_final['artist_career_duration_years'].fillna(0, inplace=True)
print("\nПропущенные значения в колонке 'artist_career_duration_years' заполнены нулями.")

# Заполняем пропуски в 'album_age_years_capped' медианой
median_album_age = df_final['album_age_years_capped'].median()
df_final['album_age_years_capped'].fillna(median_album_age, inplace=True)
print(f"Пропущенные значения в колонке 'album_age_years_capped' заполнены медианой: {median_album_age:.2f}.")

print("\nПосле обработки пропущенных значений:")
print(df_final[['artist_career_duration_years', 'album_age_years_capped']].isnull().sum())

# Финальная проверка на наличие пропущенных значений во всем датафрейме
total_missing_after_imputation = df_final.isnull().sum().sum()
if total_missing_after_imputation == 0:
    print("\nВсе пропущенные значения в df_final успешно обработаны.")
else:
    print(f"\nОстались {total_missing_after_imputation} пропущенных значений в df_final.")
    print("Колонки с оставшимися пропусками:")
    print(df_final.isnull().sum()[df_final.isnull().sum() > 0])

columns_to_remove = ['name', 'artists', 'album']
df_final = df_final.drop(columns=columns_to_remove)

print(f"Original columns {', '.join(columns_to_remove)} removed from DataFrame.")
print("\nUpdated DataFrame info:")
df_final.info()

"""### Feature Selection based on Correlation

Now that we have the correlation matrix, we can use it to select features. We will primarily look for features that are highly correlated with our target variable, `popularity_capped`, and identify features that are highly correlated with each other (multicollinearity) to potentially remove redundant ones.
"""

# Get correlations with the target variable 'popularity_capped'
correlation_with_target = df_final.corrwith(df_final['popularity_capped']).sort_values(ascending=False)

print("Корреляция признаков с целевой переменной 'popularity_capped':")
display(correlation_with_target.head(10))
display(correlation_with_target.tail(5))

# Visualize correlations with the target
plt.figure(figsize=(10, 8))
sns.barplot(x=correlation_with_target.index, y=correlation_with_target.values, palette='coolwarm')
plt.xticks(rotation=90)
plt.title('Корреляция признаков с popularity_capped')
plt.ylabel('Коэффициент корреляции')
plt.xlabel('Признак')
plt.tight_layout()
plt.show()

"""#Вывод:

*   Самый важный фактор - активность исполнителя (+0,195), активные исполнители популярнее

*   Географический фактор: США (+0,145) - крупнейший рынок музыки, Корея (+0,099) - влияние k-pop, Пуэрто-Рико (+0,088) - реггентон, Нигерия (+0,075) - афробит.
*   Жанровые предпочтения: Hip-hop/R&B/Soul (+0,114) - самый популярный жанр, Electronic/Pop (-0,106) - наименее популярный
*   Тип исполнителя: Соло-исполнители (+0,103) популярнее групп
*   Характеристики трека: длительность (+0,072) - слабое влияние, Explicit-контент (+0,071) - слабое положительное влияние

### Feature Selection: Filtering by Correlation with Targe
Отберем признаки, у которых модуль коэффициента корреляции с целевой переменной `popularity_capped` превышает 0,03. Цель этого шага — сохранить только наиболее значимые признаки для прогнозирования популярности.
"""

import numpy as np

# Calculate the absolute correlation of all features with 'popularity_capped'
absolute_correlations = df_final.corrwith(df_final['popularity_capped']).abs().sort_values(ascending=False)

# Define the correlation threshold
correlation_threshold = 0.03

# Get features with absolute correlation greater than the threshold
selected_features_by_corr = absolute_correlations[absolute_correlations > correlation_threshold].index.tolist()

# Ensure the target variable itself is included in the selected features
if 'popularity_capped' not in selected_features_by_corr:
    selected_features_by_corr.append('popularity_capped')

print(f"Features selected based on absolute correlation > {correlation_threshold} with 'popularity_capped':")
for feature in selected_features_by_corr:
    print(f"- {feature}: {absolute_correlations[feature]:.4f}")

# Create a new DataFrame with only the selected features
df_final_selected = df_final[selected_features_by_corr].copy()

print(f"\nShape of df_final_selected after correlation-based feature selection: {df_final_selected.shape}")
print("Info of the selected DataFrame:")
df_final_selected.info()

display(df_final)

"""### Разделение датасета на обучающую и тестовую выборки

Теперь, когда мы отобрали наиболее релевантные признаки, следующим шагом будет разделение данных на обучающую и тестовую выборки. Это позволит нам оценить производительность модели на независимых данных.
"""

from sklearn.model_selection import train_test_split

# Определяем целевую переменную (y) и признаки (X)
X = df_final_selected.drop('popularity_capped', axis=1)
y = df_final_selected['popularity_capped']

# Разделяем данные на обучающую (80%) и тестовую (20%) выборки
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Размер X_train: {X_train.shape}")
print(f"Размер X_test: {X_test.shape}")
print(f"Размер y_train: {y_train.shape}")
print(f"Размер y_test: {y_test.shape}")

"""### Training a Linear Regression Model"""

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Initialize and train the Linear Regression model
linear_model = LinearRegression()
linear_model.fit(X_train, y_train)

print("Linear Regression model trained successfully!")

"""### Model Evaluation and Coefficients"""

# Make predictions on the training and test sets
y_train_pred = linear_model.predict(X_train)
y_test_pred = linear_model.predict(X_test)

# Calculate metrics for the training set
mse_train = mean_squared_error(y_train, y_train_pred)
rmse_train = np.sqrt(mse_train)
r2_train = r2_score(y_train, y_train_pred)

# Calculate metrics for the test set
mse_test = mean_squared_error(y_test, y_test_pred)
rmse_test = np.sqrt(mse_test)
r2_test = r2_score(y_test, y_test_pred)

print("--- Training Set Metrics ---")
print(f"Mean Squared Error (MSE): {mse_train:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse_train:.4f}")
print(f"R-squared (R2): {r2_train:.4f}")

print("\n--- Test Set Metrics ---")
print(f"Mean Squared Error (MSE): {mse_test:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse_test:.4f}")
print(f"R-squared (R2): {r2_test:.4f}")

print("\n--- Model Coefficients ---")
coefficients_df = pd.DataFrame({'Feature': X.columns, 'Coefficient': linear_model.coef_})
display(coefficients_df)
print(f"Intercept: {linear_model.intercept_:.4f}")

"""### Training a Ridge Regression Model

Now, let's train a Ridge regression model. Ridge regression is a regularized linear regression model that adds an L2 penalty to the loss function, which helps prevent overfitting by shrinking the coefficients towards zero.
"""

from sklearn.linear_model import Ridge

# Initialize and train the Ridge Regression model (you can adjust the alpha parameter)
ridge_model = Ridge(alpha=1.0, random_state=42) # alpha is the regularization strength
ridge_model.fit(X_train, y_train)

print("Ridge Regression model trained successfully!")

"""### Ridge Model Evaluation and Coefficients

Let's evaluate the performance of the Ridge regression model on both the training and test sets, and examine its coefficients.
"""

# Make predictions on the training and test sets using the Ridge model
y_train_pred_ridge = ridge_model.predict(X_train)
y_test_pred_ridge = ridge_model.predict(X_test)

# Calculate metrics for the training set (Ridge)
mse_train_ridge = mean_squared_error(y_train, y_train_pred_ridge)
rmse_train_ridge = np.sqrt(mse_train_ridge)
r2_train_ridge = r2_score(y_train, y_train_pred_ridge)

# Calculate metrics for the test set (Ridge)
mse_test_ridge = mean_squared_error(y_test, y_test_pred_ridge)
rmse_test_ridge = np.sqrt(mse_test_ridge)
r2_test_ridge = r2_score(y_test, y_test_pred_ridge)

print("--- Ridge Regression - Training Set Metrics ---")
print(f"Mean Squared Error (MSE): {mse_train_ridge:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse_train_ridge:.4f}")
print(f"R-squared (R2): {r2_train_ridge:.4f}")

print("\n--- Ridge Regression - Test Set Metrics ---")
print(f"Mean Squared Error (MSE): {mse_test_ridge:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse_test_ridge:.4f}")
print(f"R-squared (R2): {r2_test_ridge:.4f}")

print("\n--- Ridge Model Coefficients ---")
coefficients_ridge_df = pd.DataFrame({'Feature': X.columns, 'Coefficient': ridge_model.coef_})
display(coefficients_ridge_df)
print(f"Intercept: {ridge_model.intercept_:.4f}")

"""Модель недообучена, так как объясняет только 12,84% популярности.

### Training a Lasso Regression Model

Next, we will train a Lasso regression model. Lasso (Least Absolute Shrinkage and Selection Operator) is another regularized linear model that adds an L1 penalty, which can lead to sparse models by driving some coefficients exactly to zero, effectively performing feature selection.
"""

from sklearn.linear_model import Lasso

# Initialize and train the Lasso Regression model (you can adjust the alpha parameter)
lasso_model = Lasso(alpha=0.01, random_state=42) # alpha is the regularization strength
lasso_model.fit(X_train, y_train)

print("Lasso Regression model trained successfully!")

"""### Lasso Model Evaluation and Coefficients

Let's evaluate the performance of the Lasso regression model on both the training and test sets, and examine its coefficients.
"""

# Make predictions on the training and test sets using the Lasso model
y_train_pred_lasso = lasso_model.predict(X_train)
y_test_pred_lasso = lasso_model.predict(X_test)

# Calculate metrics for the training set (Lasso)
mse_train_lasso = mean_squared_error(y_train, y_train_pred_lasso)
rmse_train_lasso = np.sqrt(mse_train_lasso)
r2_train_lasso = r2_score(y_train, y_train_pred_lasso)

# Calculate metrics for the test set (Lasso)
mse_test_lasso = mean_squared_error(y_test, y_test_pred_lasso)
rmse_test_lasso = np.sqrt(mse_test_lasso)
r2_test_lasso = r2_score(y_test, y_test_pred_lasso)

print("--- Lasso Regression - Training Set Metrics ---")
print(f"Mean Squared Error (MSE): {mse_train_lasso:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse_train_lasso:.4f}")
print(f"R-squared (R2): {r2_train_lasso:.4f}")

print("\n--- Lasso Regression - Test Set Metrics ---")
print(f"Mean Squared Error (MSE): {mse_test_lasso:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse_test_lasso:.4f}")
print(f"R-squared (R2): {r2_test_lasso:.4f}")

print("\n--- Lasso Model Coefficients ---")
coefficients_lasso_df = pd.DataFrame({'Feature': X.columns, 'Coefficient': lasso_model.coef_})
display(coefficients_lasso_df)
print(f"Intercept: {lasso_model.intercept_:.4f}")

"""### Сравнение результатов всех трёх моделей

Давайте сравним метрики производительности (MSE и R-squared) и коэффициенты для всех трех обученных линейных моделей: Стандартной Линейной Регрессии, Ridge и Lasso.
"""

print("### Сводка по метрикам производительности ###\n")

print("**Линейная Регрессия:**")
print(f"  MSE (Train): {mse_train:.4f}, RMSE (Train): {rmse_train:.4f}, R2 (Train): {r2_train:.4f}")
print(f"  MSE (Test): {mse_test:.4f}, RMSE (Test): {rmse_test:.4f}, R2 (Test): {r2_test:.4f}")

print("\n**Ridge Регрессия:**")
print(f"  MSE (Train): {mse_train_ridge:.4f}, RMSE (Train): {rmse_train_ridge:.4f}, R2 (Train): {r2_train_ridge:.4f}")
print(f"  MSE (Test): {mse_test_ridge:.4f}, RMSE (Test): {rmse_test_ridge:.4f}, R2 (Test): {r2_test_ridge:.4f}")

print("\n**Lasso Регрессия:**")
print(f"  MSE (Train): {mse_train_lasso:.4f}, RMSE (Train): {rmse_train_lasso:.4f}, R2 (Train): {r2_train_lasso:.4f}")
print(f"  MSE (Test): {mse_test_lasso:.4f}, RMSE (Test): {rmse_test_lasso:.4f}, R2 (Test): {r2_test_lasso:.4f}")

print("\n\n### Сравнение Коэффициентов Моделей ###\n")

# Объединяем коэффициенты в один DataFrame для удобства сравнения
all_coefficients_df = pd.DataFrame({'Feature': X.columns})
all_coefficients_df['Linear Regression Coef'] = linear_model.coef_
all_coefficients_df['Ridge Coef (alpha=1.0)'] = ridge_model.coef_
all_coefficients_df['Lasso Coef (alpha=0.01)'] = lasso_model.coef_

display(all_coefficients_df)

print(f"\nИнтерсепт Линейной Регрессии: {linear_model.intercept_:.4f}")
print(f"Интерсепт Ridge Регрессии: {ridge_model.intercept_:.4f}")
print(f"Интерсепт Lasso Регрессии: {lasso_model.intercept_:.4f}")

"""#### Выводы:

*   **Производительность:** Все три модели показывают очень схожие результаты по метрикам MSE и R-squared как на обучающей, так и на тестовой выборках. Значения R-squared (около 0.16 на тренировочных данных и 0.13 на тестовых данных) указывают на то, что эти линейные модели объясняют лишь небольшую часть дисперсии в целевой переменной `popularity_capped`.
*   **Переобучение/Недообучение:** Разница между метриками на тренировочных и тестовых данных минимальна, что свидетельствует об отсутствии явного переобучения. Однако, низкие значения R-squared указывают на возможное недообучение (модели слишком просты для данных) или на то, что факторы, влияющие на популярность, не полностью улавливаются выбранными признаками и линейными зависимостями.
*   **Коэффициенты:**
    *   **Линейная Регрессия** и **Ridge Регрессия** имеют очень похожие коэффициенты, что ожидаемо, так как Ridge с `alpha=1.0` оказывает умеренное воздействие на коэффициенты, не сильно их обнуляя. Это подтверждает, что в данном случае сильной мультиколлинеарности, которую Ridge должен был бы сильно подавить, не наблюдается, или же она не сильно влияет на эту метрику.
    *   **Lasso Регрессия** с `alpha=0.01` также демонстрирует коэффициенты, очень близкие к другим моделям, но при более высоком `alpha` Lasso мог бы обнулить некоторые коэффициенты, выполняя таким образом отбор признаков. В текущей конфигурации `alpha` слишком мал, чтобы вызвать значительное обнуление коэффициентов. Тем не менее, можно заметить очень незначительные отличия в значениях по сравнению с линейной и Ridge регрессией.

### Обучение модели SVM Regressor

Теперь перейдем к обучению более сложной модели - SVM Regressor (Support Vector Machine for Regression). SVM Regressor может улавливать нелинейные зависимости в данных и часто показывает хорошую производительность. Для начала будем использовать параметры по умолчанию.
"""

from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR

# Масштабирование признаков (важно для SVR)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

svm_model = SVR(
    kernel='rbf',
    C=10.0,           # Увеличили для уменьшения регуляризации
    epsilon=0.01,     # Уменьшили для более точной аппроксимации
    gamma='scale'     # Автоматический подбор gamma
)
# kernel='rbf' (Radial Basis Function) - часто хороший выбор для нелинейных данных
# C - параметр регуляризации (чем больше C, тем меньше регуляризация)
# epsilon - ширина 'трубы' для ошибок в функции потерь

print("Обучение SVM Regressor... Это может занять некоторое время.")
svm_model.fit(X_train_scaled, y_train)

print("SVM Regressor модель успешно обучена!")

"""### Оценка SVM Regressor и выводы о переобучении/недообучении

Оценим производительность обученной SVM Regressor на обучающей и тестовой выборках, а также сделаем выводы о потенциальном переобучении или недообучении.
"""

# Прогнозы на обучающей и тестовой выборках с помощью SVM модели
y_train_pred_svm = svm_model.predict(X_train_scaled)
y_test_pred_svm = svm_model.predict(X_test_scaled)

# Расчет метрик для обучающей выборки (SVM)
mse_train_svm = mean_squared_error(y_train, y_train_pred_svm)
rmse_train_svm = np.sqrt(mse_train_svm)
r2_train_svm = r2_score(y_train, y_train_pred_svm)

# Расчет метрик для тестовой выборки (SVM)
mse_test_svm = mean_squared_error(y_test, y_test_pred_svm)
rmse_test_svm = np.sqrt(mse_test_svm)
r2_test_svm = r2_score(y_test, y_test_pred_svm)

print("--- SVM Regressor - Метрики на обучающей выборке ---")
print(f"Среднеквадратичная ошибка (MSE): {mse_train_svm:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse_train_svm:.4f}")
print(f"Коэффициент детерминации (R-squared): {r2_train_svm:.4f}")

print("\n--- SVM Regressor - Метрики на тестовой выборке ---")
print(f"Среднеквадратичная ошибка (MSE): {mse_test_svm:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse_test_svm:.4f}")
print(f"Коэффициент детерминации (R-squared): {r2_test_svm:.4f}")

print("\n--- Выводы о переобучении/недообучении (SVM Regressor) ---")
if r2_train_svm > r2_test_svm and (r2_train_svm - r2_test_svm) > 0.1: # Порог для разницы можно настраивать
    print("Модель SVM Regressor, возможно, переобучается: производительность на обучающей выборке значительно выше, чем на тестовой.")
elif r2_train_svm < 0.1 and r2_test_svm < 0.1:
    print("Модель SVM Regressor, возможно, недообучается: значения R-squared очень низкие на обеих выборках.")
else:
    print("Модель SVM Regressor показывает сопоставимую производительность на обучающей и тестовой выборках, что говорит об отсутствии сильного переобучения или недообучения, но общая объясняющая способность модели невысока.")

"""### Выводы:

*   SVM regressor недообучился, показатели R2 на обучающей и тестовой выборке крайней малы (0,0270 и 0,0322)
*   Возможные причины: отсутствие масштабирования данных, неоптимальные параметры (C, gamma, epsilion), плохо работает с категориальными данными


"""

model_names = [
    "Linear Regression",
    "Ridge Regression",
    "Lasso Regression",
    "SVM Regressor"
]

mse_train_values = [
    mse_train,
    mse_train_ridge,
    mse_train_lasso,
    mse_train_svm
]

rmse_train_values = [
    rmse_train,
    rmse_train_ridge,
    rmse_train_lasso,
    rmse_train_svm
]

r2_train_values = [
    r2_train,
    r2_train_ridge,
    r2_train_lasso,
    r2_train_svm
]

mse_test_values = [
    mse_test,
    mse_test_ridge,
    mse_test_lasso,
    mse_test_svm
]

rmse_test_values = [
    rmse_test,
    rmse_test_ridge,
    rmse_test_lasso,
    rmse_test_svm
]

r2_test_values = [
    r2_test,
    r2_test_ridge,
    r2_test_lasso,
    r2_test_svm
]

summary_df = pd.DataFrame({
    'Model': model_names,
    'MSE (Train)': mse_train_values,
    'RMSE (Train)': rmse_train_values,
    'R2 (Train)': r2_train_values,
    'MSE (Test)': mse_test_values,
    'RMSE (Test)': rmse_test_values,
    'R2 (Test)': r2_test_values
})

print("### Сводная таблица метрик качества моделей ###")
display(summary_df.round(4))

print("\n--- Выводы по моделям ---")
print("Линейные модели (Linear, Ridge, Lasso) показывают очень схожую, но низкую производительность (R2 около 0.13-0.16), что указывает на недообучение. Разница между тренировочными и тестовыми метриками минимальна, то есть переобучения нет.")
print("SVM Regressor демонстрирует немного лучшую производительность (R2 около 0.20-0.28), но всё ещё достаточно низкую для хорошей объясняющей способности. Разница между тренировочными и тестовыми R2 для SVM больше, чем для линейных моделей, но не критично, что указывает на умеренное улучшение в понимании данных, но всё ещё возможное недообучение или необходимость дальнейшей настройки параметров и/или усложнения модели. "
)

"""### SHAP анализ на модели SVM Regressor

Для того чтобы понять, какие признаки оказывают наибольшее влияние на предсказания модели SVM Regressor, проведем SHAP анализ. SHAP (SHapley Additive exPlanations) объясняет выход модели, вычисляя вклад каждого признака в предсказание для отдельного экземпляра данных.
"""

import shap

# Инициализация SHAP-эксплейнера
# Для моделей на основе ядра (kernel-based models) как SVR, KernelExplainer подходит лучше.
# Однако, он может быть очень медленным на больших наборах данных.
# Для начала, попробуем с KernelExplainer на небольшой подвыборке тестовых данных.
# Если будет слишком долго, можно рассмотреть другие варианты или уменьшить sample_size.

# Поскольку KernelExplainer требует фонового датасета, используем подвыборку из X_train
# Для ускорения, возьмем небольшую часть X_test для объяснений
sample_size = 100 # Объясняем 100 случайных образцов из тестового набора
X_test_sample = X_test.sample(n=sample_size, random_state=42)

print(f"Инициализация SHAP KernelExplainer для {sample_size} образцов из X_test... Это может занять некоторое время.")
explainer = shap.KernelExplainer(svm_model.predict, X_train.sample(n=50, random_state=42))

# Вычисление SHAP-значений для выборки тестовых данных
shap_values = explainer.shap_values(X_test_sample)

print("SHAP значения вычислены!")

"""### Визуализация результатов SHAP анализа

Теперь, когда у нас есть SHAP-значения, мы можем визуализировать их для получения инсайтов о работе модели. Мы используем следующие типы графиков:
"""

# 1. Summary Plot (сводный график) - показывает важность каждого признака и его влияние на предсказания
print("Генерация SHAP Summary Plot...")
plt.figure(figsize=(12, 8))
shap.summary_plot(
    shap_values,
    X_test_sample,
    feature_names=X.columns.tolist(),
    plot_type="bar",
    show=False            # ✅ Не показываем сразу, чтобы добавить заголовок
)
plt.title("SHAP Summary Plot (Bar) - Важность признаков")
plt.tight_layout()
plt.show()

# 2. Summary Plot (dot plot) - показывает распределение SHAP-значений для каждого признака
# Цвет точек указывает на значение признака (красный = высокое, синий = низкое)
print("Генерация SHAP Summary Plot (Dot)...")
shap.summary_plot(shap_values, X_test_sample, show=False)
plt.title("SHAP Summary Plot (Dot)")
plt.tight_layout()
plt.show()

# 3. Force Plot для одного экземпляра - объясняет предсказание отдельного примера
print("Генерация SHAP Force Plot для первого экземпляра...")
# Выберем первый пример из нашей выборки для объяснения
i = 0
sample_data = X_test_sample.iloc[i]
sample_shap = shap_values[i]

print(f"Пример #{i}:")
print(f"  Реальная популярность: {y_test.iloc[i]:.2f}")
print(f"  Предсказанная популярность: {svm_model.predict(X_test.iloc[[i]])[0]:.2f}")
print(f"  Базовое значение: {explainer.expected_value:.2f}")

# Force Plot (может не работать в некоторых версиях shap)
try:
    # Современный способ
    shap.force_plot(
        explainer.expected_value,
        sample_shap,
        sample_data,
        feature_names=X.columns.tolist(),
        matplotlib=True,
        show=False
    )
    plt.title(f"SHAP Force Plot для примера #{i}")
    plt.tight_layout()
    plt.show()
except Exception as e:
    print(f"Force Plot не сработал: {e}")

    # Альтернатива: Waterfall Plot
    try:
        print("Используем Waterfall Plot...")
        shap.waterfall_plot(
            shap.Explanation(
                values=sample_shap,
                base_values=explainer.expected_value,
                data=sample_data,
                feature_names=X.columns.tolist()
            ),
            show=False
        )
        plt.title(f"SHAP Waterfall Plot для примера #{i}")
        plt.tight_layout()
        plt.show()
    except Exception as e2:
        print(f"Waterfall Plot тоже не сработал: {e2}")
print("SHAP анализ завершен. Визуализации должны помочь понять влияние признаков.")

import shap
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# 1. ИСПРАВЛЕНО: Увеличиваем фоновый датасет для стабильности
background_size = 100  # Увеличиваем с 50 до 100
X_background = X_train.sample(n=background_size, random_state=42)

print(f"Инициализация SHAP KernelExplainer с {background_size} фоновыми образцами...")

# 2. ИСПРАВЛЕНО: Явно указываем функцию предсказания
def predict_wrapper(x):
    """Обертка для predict, которая обрабатывает pandas DataFrame"""
    if isinstance(x, pd.DataFrame):
        return svm_model.predict(x)
    return svm_model.predict(x)

explainer = shap.KernelExplainer(
    predict_wrapper,
    X_background,
    link="identity"  # Для регрессии
)

# 3. Уменьшаем размер тестовой выборки для ускорения
sample_size = 50  # Уменьшаем для скорости
X_test_sample = X_test.sample(n=sample_size, random_state=42)

print("Вычисление SHAP значений... Это может занять 5-10 минут...")
shap_values = explainer.shap_values(X_test_sample, nsamples=100)  # Уменьшаем nsamples для скорости

print(f"SHAP значения вычислены! Форма: {np.array(shap_values).shape}")

# Проверка: есть ли ненулевые SHAP значения?
if np.all(np.abs(shap_values) < 1e-6):
    print("⚠️ ВНИМАНИЕ: Все SHAP значения близки к нулю!")
    print("Модель SVR не может быть объяснена через SHAP из-за низкого качества.")
    print("Рекомендуется обучить более мощную модель (XGBoost/Random Forest).")
else:
    print(f"✅ SHAP значения успешно вычислены. Диапазон: [{shap_values.min():.4f}, {shap_values.max():.4f}]")

# 4. ВИЗУАЛИЗАЦИИ

# 4.1 Bar Plot - глобальная важность признаков
print("\nГенерация SHAP Summary Plot (Bar)...")
plt.figure(figsize=(10, 8))
shap.summary_plot(
    shap_values,
    X_test_sample,
    feature_names=X.columns.tolist(),
    plot_type="bar",
    show=False
)
plt.title("Глобальная важность признаков (SHAP)")
plt.xlabel("Среднее абсолютное значение SHAP")
plt.tight_layout()
plt.show()

# 4.2 Dot Plot - распределение влияния признаков
print("\nГенерация SHAP Summary Plot (Dot)...")
plt.figure(figsize=(10, 8))
shap.summary_plot(
    shap_values,
    X_test_sample,
    feature_names=X.columns.tolist(),
    show=False
)
plt.title("Распределение SHAP значений по признакам")
plt.tight_layout()
plt.show()

# 4.3 ТОП-10 признаков с таблицей
print("\n--- ТОП-10 важнейших признаков ---")
shap_importance = np.abs(shap_values).mean(axis=0)
feature_importance = pd.DataFrame({
    'Feature': X.columns.tolist(),
    'Mean |SHAP|': shap_importance
}).sort_values('Mean |SHAP|', ascending=False)

print(feature_importance.head(10).to_string(index=False))

# 4.4 Force Plot для экземпляра с максимальной ошибкой
print("\nГенерация SHAP Force Plot для экземпляра с максимальной ошибкой...")

# Находим экземпляр с максимальной ошибкой
errors = abs(y_test.loc[X_test_sample.index] - svm_model.predict(X_test_sample))
max_error_idx = errors.idxmax()
max_error_instance = X_test_sample.loc[[max_error_idx]]
max_error_shap = shap_values[X_test_sample.index.get_loc(max_error_idx)]

actual_value = y_test.loc[max_error_idx]
predicted_value = svm_model.predict(max_error_instance)[0]

print(f"Экземпляр с макс. ошибкой (индекс {max_error_idx}):")
print(f"  Факт: {actual_value:.2f}")
print(f"  Предсказание: {predicted_value:.2f}")
print(f"  Ошибка: {abs(actual_value - predicted_value):.2f}")
print(f"  Базовое значение (expected): {explainer.expected_value:.2f}")

# Проверяем, что SHAP сумма равна разнице между предсказанием и базовым значением
sum_shap = np.sum(max_error_shap)
print(f"  Сумма SHAP значений: {sum_shap:.4f}")
print(f"  Предсказание = базовое + сумма SHAP: {explainer.expected_value:.2f} + {sum_shap:.4f} = {explainer.expected_value + sum_shap:.2f}")

# Force Plot
try:
    shap.force_plot(
        explainer.expected_value,
        max_error_shap,
        max_error_instance.values[0],
        feature_names=X.columns.tolist(),
        matplotlib=True,
        show=False
    )
    plt.title(f"SHAP Force Plot для экземпляра с макс. ошибкой\n(Факт: {actual_value:.2f}, Пред: {predicted_value:.2f})")
    plt.tight_layout()
    plt.show()
except Exception as e:
    print(f"Force Plot не сработал: {e}")

    # Waterfall Plot как альтернатива
    try:
        print("Используем Waterfall Plot...")
        shap.waterfall_plot(
            shap.Explanation(
                values=max_error_shap,
                base_values=explainer.expected_value,
                data=max_error_instance.values[0],
                feature_names=X.columns.tolist()
            ),
            show=False
        )
        plt.title(f"SHAP Waterfall Plot для экземпляра с макс. ошибкой")
        plt.tight_layout()
        plt.show()
    except Exception as e2:
        print(f"Waterfall Plot тоже не сработал: {e2}")

print("\n✅ SHAP анализ завершен!")

"""Модель предсказывает константу 26,57 (среднее значение целевой переменной в обучающей выборке) для всех экземпляров

### LIME анализ для примера с большой ошибкой SVM Regressor

Чтобы глубже понять, почему модель SVM Regressor дала большую ошибку на конкретном примере, мы проведем LIME (Local Interpretable Model-agnostic Explanations) анализ. LIME позволяет объяснить предсказание модели для отдельного экземпляра данных, выделяя признаки, которые в наибольшей степени повлияли на это предсказание.
"""

pip install lime

import lime
import lime.lime_tabular
import matplotlib.pyplot as plt

# 1. Находим экземпляр с наибольшей ошибкой в тестовом наборе
errors = abs(y_test - y_test_pred_svm)
max_error_idx_in_test_subset = errors.idxmax() # Индекс из исходного df_final_selected

# Получаем соответствующую строку из X_test и фактические/предсказанные значения
instance_to_explain = X_test.loc[max_error_idx_in_test_subset]
actual_value = y_test.loc[max_error_idx_in_test_subset]
predicted_value = svm_model.predict(instance_to_explain.to_frame().T)[0]

print(f"Индекс экземпляра с наибольшей ошибкой в тестовом наборе: {max_error_idx_in_test_subset}")
print(f"Фактическое значение популярности: {actual_value:.2f}")
print(f"Предсказанное значение популярности: {predicted_value:.2f}")
print(f"Абсолютная ошибка: {abs(actual_value - predicted_value):.2f}")

# 2. Подготовка данных для LIME Explainer
feature_names = X_train.columns.tolist()

# Определяем индексы категориальных признаков. Для LIME все one-hot закодированные
# столбцы и бинарные (0/1) столбцы рассматриваются как категориальные.
# В нашем случае большинство int64 столбцов являются бинарными (OHE или булевы).
categorical_features_indices = [i for i, col in enumerate(X_train.columns) if X_train[col].dtype == 'int64']

# Инициализация LIME explainer
explainer = lime.lime_tabular.LimeTabularExplainer(
    training_data=X_train.values, # Обучающие данные для понимания распределения признаков
    feature_names=feature_names,
    class_names=['popularity_capped'], # Целевое имя для контекста регрессии
    categorical_features=categorical_features_indices,
    mode='regression',
    discretize_continuous=True # Дискретизация непрерывных признаков для лучшего объяснения
)

# 3. Генерация LIME объяснения для выбранного экземпляра
num_features_to_show = 10 # Количество признаков для отображения в объяснении
print(f"\nГенерация LIME объяснения для экземпляра {max_error_idx_in_test_subset}...")
explanation = explainer.explain_instance(
    data_row=instance_to_explain.values,
    predict_fn=svm_model.predict,
    num_features=num_features_to_show
)

print("\nLIME объяснение (топ-10 признаков):")
for feature, weight in explanation.as_list():
    print(f"- {feature}: {weight:.4f}")

# 4. Визуализация LIME объяснения
print("\nВизуализация LIME объяснения...")
plt.figure(figsize=(12, 8))
explanation.as_pyplot_figure()
plt.title(f"LIME Explanation for instance {max_error_idx_in_test_subset} (Actual: {actual_value:.2f}, Predicted: {predicted_value:.2f})")
plt.tight_layout()
plt.show()

"""LIME показала нулевые веса, так как коэффициент детерминации модели R2 = 0,2 и модель не может найти значимые закономерности.

###Выводы:


*   Все 4 модели показвают низкие результаты, R2 на тестовой выборке 0,13-0,2. Наилучшие результаты демонстрирует SVM Regressor.
*   Линейные модели (Linear, Ridge, Lasso) показывают почти одинаковые метрики. Ridge и Lasso не дали улучшения по сравнению с обычной линейной регрессией. Это указывает, что проблема не в регуляризации, а в самой структуре данных.
*   Причинами низкого качества моделей может служить недостаточная информативность признаков (признаки слабо коррелируют с целевой переменной)
"""